In [18]:
import pandas as pd
from pandas.plotting import radviz
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
#import the model we are using
from sklearn.ensemble import RandomForestRegressor
from sklearn import svm, preprocessing
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_squared_error, mean_absolute_error, explained_variance_score

In [19]:
def read(file):
    return pd.read_csv(file)

#features.set_index(['Index'], inplace = True)
#features.drop(columns = ['Index'], inplace = True)

features = read('Pmax_backward_Final 1.csv')
features.head(5)

α [°]  H [mm]   b [mm]    Ls [mm]  d [mm]  γ [N/mm3]   Pmax [N]  \
0     15    90.0  19.4114  17.555563     5.0   0.000016   9.080644   
1     15    90.0  12.9410  41.703709     5.0   0.000016   8.758713   
2     15    90.0  19.4114  17.555563     5.0   0.000016  11.753734   
3     15    90.0  12.9410  41.703709     5.0   0.000016  10.797683   
4     15    90.0  19.4114  17.555563     5.0   0.000016  14.095079   

    Vroot [mm3]  DR [ ]  
0   4534.350557     0.8  
1   3535.876732     0.8  
2   8267.564868     0.8  
3   5796.469487     0.8  
4  23281.011643     0.8

In [20]:
def print_shape(data):
    print("The shape of our feature is " + str(data.shape))

print_shape(features)

The shape of our feature is (177, 9)


In [21]:
#summary statistics
features.describe()
features.columns.values

array(['α [°]', 'H [mm]', 'b [mm]', 'Ls [mm]', 'd [mm]', 'γ [N/mm3]',
       'Pmax [N]', 'Vroot [mm3]', 'DR [ ]'], dtype=object)

In [22]:
#pd.options.display.max_rows = 181
pd.options.display.max_columns = 30
#features.sort_values(by = "L [mm]", ascending = True, inplace = True)
#display(features)

In [23]:
#one hot encoding
pd.options.display.max_columns = 181
pd.options.display.max_rows = 181

if 'n [count]' in features.columns and 'Material' in features.columns:
    features = pd.get_dummies(features, columns = ['n [count]', 'Material'])
elif 'n [count]' in features.columns:
    features = pd.get_dummies(features, columns = ['n [count]'])
elif 'Material' in features.columns:
    features = pd.get_dummies(features, columns = ['Material'])
#features.head(5)
#display(features)
#print_shape(features)

In [24]:


#target pmax/f
pmax = np.array(features['f'])
#Remove labels from the features
features = features.drop('f', axis = 1)
feature_list = list(features.columns)
features = StandardScaler().fit_transform(features)
#pca = PCA(n_components = 11)
#principalComponents = pca.fit_transform(features)
#features = pd.DataFrame(data = principalComponents, columns = ['pc1', 'pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10','pc11'])
#display(features)
#print(pca.explained_variance_ratio_.cumsum())

#Covert to numpy arrays
features = np.array(features)



#print(features)
print_shape(features)

KeyError: 'f'

In [ ]:
#split the data into training set and testing set 
train_features, test_features, train_labels, test_labels = train_test_split(features, pmax, test_size = 0.25, random_state = 42)

In [25]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (132, 16)
Training Labels Shape: (132,)
Testing Features Shape: (45, 16)
Testing Labels Shape: (45,)


In [26]:
#Establish Baseline

In [27]:
#instantiate the model 
rf = RandomForestRegressor(n_estimators = 1000, random_state = 42)
# n_estimator is lambda
# use cross validation to optimize the n_estimators 
# use k_fold
#change the n_estimator to discover the difference 
#SVM, SVR, knernel RBF, logistic regression, naive base (compare between gernerateive method and discrimitive method)
#ensemble method(random bagging)
#plot those regression
#PCA Get the result (visualize it)
# --> classfication using high value, mid value, low value
#train the model on training data

#cumulate the features to see the result
rf.fit(train_features, train_labels)

RandomForestRegressor(n_estimators=1000, random_state=42)

In [28]:
import math
#Make Predictions
#Use the forest's predict method on the test data 
predictions = rf.predict(test_features)

#Calculate the absolute errors
errors = abs(predictions - test_labels)

mean_absolute_error = mean_absolute_error(test_labels, predictions)



#print out the mean absolute error
print('Mean Absolute Error:', round(mean_absolute_error, 5))

Mean Absolute Error: 0.03797


In [1280]:
mean_square_error = mean_squared_error(test_labels, predictions, squared=False)

print("Mean Square Error: ", round(mean_square_error, 5))

Mean Square Error:  0.05275


In [1281]:
explained_variance_score = explained_variance_score(test_labels, predictions)

print("Explained variance score: ", round(explained_variance_score, 7))

Explained variance score:  0.8863779


In [669]:
#from sklearn.tree import export_graphviz
#import pydot

In [502]:
#tree = rf.estimators_[5]
#export_graphviz(tree, out_file = "tree.dot", feature_names = feature_list, rounded = True, precision = 1)
#(graph, ) = pydot.graph_from_dot_file("tree.dot")
#graph.write_png("tree.png")

## Kernel RBF

In [79]:
#kernel (rbf)
clf = svm.SVR(kernel = "rbf")
clf.fit(train_features,train_labels)
print(clf.score(train_features, train_labels))

0.8346516102871083


//anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [80]:

errors = 0
for X,y in zip(test_features, test_labels):
    print(f"Model: {clf.predict([X])[0]}, Actual: {y}")
    errors += abs(clf.predict([X])[0] - y)
errors = errors / test_features.shape[0]

print('Mean Absolute error:',round(errors, 2) , 'newton.')

# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')



Model: 0.8331319308659725, Actual: 0.933933933933934
Model: 0.5318553619630471, Actual: 0.4904904904904905
Model: 0.8716322541153154, Actual: 0.947947947947948
Model: 0.5347766842024957, Actual: 0.5295295295295295
Model: 0.9320030233089158, Actual: 1.0
Model: 0.8325144261122042, Actual: 0.7677677677677678
Model: 0.8691317059268557, Actual: 0.8658658658658659
Model: 0.5827624567921297, Actual: 0.5935935935935935
Model: 0.6763077772327766, Actual: 0.4924924924924925
Model: 0.879608826324751, Actual: 1.0
Model: 0.7269150801120968, Actual: 0.6636636636636637
Model: 0.785911501460733, Actual: 0.8028028028028028
Model: 0.8418132718998405, Actual: 0.943943943943944
Model: 0.7810788180417517, Actual: 0.7137137137137137
Model: 0.8806129842701061, Actual: 0.8438438438438438
Model: 0.8688544425343977, Actual: 1.0
Model: 0.9228303314523307, Actual: 1.0
Model: 0.6654343218014926, Actual: 0.7617617617617618
Model: 0.7723801028195016, Actual: 0.7727727727727728
Model: 0.883831021978888, Actual: 1.0
M

## Kernel Polynomial

In [81]:
clf = svm.SVR(kernel = "poly", degree = 3)
clf.fit(train_features,train_labels)
print(clf.score(train_features, train_labels))

0.7903953583908736


//anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [19]:
errors = 0
for X,y in zip(test_features, test_labels):
    print(f"Model: {clf.predict([X])[0]}, Actual: {y}")
    errors += abs(clf.predict([X])[0] - y)
errors = errors / test_features.shape[0]

print('Mean Absolute error:',round(errors, 2) , 'newton.')

# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Model: 0.8453792953186632, Actual: 0.933933933933934
Model: 0.5143828763575473, Actual: 0.4904904904904905
Model: 0.8374105591937121, Actual: 0.947947947947948
Model: 0.5892406033282486, Actual: 0.5295295295295295
Model: 0.9890917399749535, Actual: 1.0
Model: 0.8150729144225136, Actual: 0.7677677677677678
Model: 0.8111151268101853, Actual: 0.8658658658658659
Model: 0.4589822319544345, Actual: 0.5935935935935935
Model: 0.6901523965553845, Actual: 0.4924924924924925
Model: 1.0227921922878416, Actual: 1.0
Model: 0.6681396090122047, Actual: 0.6636636636636637
Model: 0.8244713213729181, Actual: 0.8028028028028028
Model: 0.8950494317483622, Actual: 0.943943943943944
Model: 0.7622310882303607, Actual: 0.7137137137137137
Model: 0.8181713083120117, Actual: 0.8438438438438438
Model: 1.047605928278367, Actual: 1.0
Model: 0.9537691938797187, Actual: 1.0
Model: 0.7764122853007435, Actual: 0.7617617617617618
Model: 0.7737775778341033, Actual: 0.7727727727727728
Model: 0.9665028744293883, Actual: 1.0

## Kernel Linear

In [20]:
clf = svm.SVR(kernel = "linear")
clf.fit(train_features,train_labels)
print(clf.score(train_features, train_labels))

0.8193209757551584


In [21]:
errors = 0
for X,y in zip(test_features, test_labels):
    print(f"Model: {clf.predict([X])[0]}, Actual: {y}")
    errors += abs(clf.predict([X])[0] - y)
errors = errors / test_features.shape[0]

print('Mean Absolute error:',round(errors, 2) , 'newton.')

# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Model: 0.944404702128944, Actual: 0.933933933933934
Model: 0.5516939082310507, Actual: 0.4904904904904905
Model: 0.8857724351683326, Actual: 0.947947947947948
Model: 0.5588487577956097, Actual: 0.5295295295295295
Model: 1.1327405574011276, Actual: 1.0
Model: 0.8073579212838075, Actual: 0.7677677677677678
Model: 0.8848744520811332, Actual: 0.8658658658658659
Model: 0.5186369603316624, Actual: 0.5935935935935935
Model: 0.7300538158640458, Actual: 0.4924924924924925
Model: 1.0403633824378318, Actual: 1.0
Model: 0.6423652648149581, Actual: 0.6636636636636637
Model: 0.8270053225431713, Actual: 0.8028028028028028
Model: 0.9522141461385761, Actual: 0.943943943943944
Model: 0.7207783791985795, Actual: 0.7137137137137137
Model: 0.8879246608009105, Actual: 0.8438438438438438
Model: 1.0453625303724117, Actual: 1.0
Model: 1.0571910669693563, Actual: 1.0
Model: 0.6732581461162842, Actual: 0.7617617617617618
Model: 0.724655777646919, Actual: 0.7727727727727728
Model: 0.995053163944582, Actual: 1.0
M

## Linear Regression

In [22]:
reg = linear_model.Ridge()
reg.fit(train_features, train_labels)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [23]:
reg.coef_

array([ 0.03737859, -0.02767442,  0.00147585, -0.05415995, -0.12139303,
       -0.01669328,  0.02018646])

In [24]:
a = reg.predict(test_features)

In [25]:
a

array([0.92343665, 0.57289554, 0.88051428, 0.6185316 , 1.08772326,
       0.82061218, 0.86988252, 0.54353425, 0.74359451, 1.03385246,
       0.65751762, 0.82371788, 0.92725092, 0.72107369, 0.87225205,
       1.03769952, 1.03468469, 0.68449076, 0.72417768, 0.9993246 ,
       0.78215024, 0.968438  , 0.84158184, 0.77433828, 0.75760516,
       0.7174791 , 0.92916442, 0.94554227, 0.75339931, 1.02407207,
       0.67184933, 1.03758029, 0.98691722, 0.91599653, 0.62426502,
       0.9441203 , 1.00133189, 0.71908492, 0.8699534 , 0.98010423,
       0.7720038 , 1.02233661, 0.63805486, 1.08260663, 0.99374708])

In [26]:
test_labels

array([0.93393393, 0.49049049, 0.94794795, 0.52952953, 1.        ,
       0.76776777, 0.86586587, 0.59359359, 0.49249249, 1.        ,
       0.66366366, 0.8028028 , 0.94394394, 0.71371371, 0.84384384,
       1.        , 1.        , 0.76176176, 0.77277277, 1.        ,
       0.72272272, 0.87587588, 0.94794795, 0.81881882, 0.76076076,
       0.7957958 , 1.        , 0.87787788, 0.78978979, 0.93493493,
       0.65065065, 1.        , 1.        , 0.94394394, 0.53653654,
       0.96896897, 1.        , 0.65765766, 0.83683684, 1.        ,
       0.65365365, 0.94594595, 0.72572573, 1.        , 1.        ])

In [27]:
np.mean(abs(test_labels - a))
print('Mean Absolute error:',round(errors, 2) , 'newton.')

Mean Absolute error: 0.05 newton.


In [28]:
# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Accuracy: 93.13 %.


## Logistic Regression

In [29]:
clf = svm.SVR(kernel = "sigmoid")
clf.fit(train_features,train_labels)
print(clf.score(train_features, train_labels))

-365.90866363042005


//anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [30]:
errors = 0
pred_pmax = []
for X,y in zip(test_features, test_labels):
    print(f"Model: {clf.predict([X])[0]}, Actual: {y}")
    errors += abs(clf.predict([X])[0] - y)
    pred_pmax.append(clf.predict([X])[0])
errors = errors / test_features.shape[0]

print('Mean Absolute error:',round(errors, 2) , 'newton.')
print(pred_pmax)
# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Model: 0.3861323400847584, Actual: 0.933933933933934
Model: 0.003346192773395318, Actual: 0.4904904904904905
Model: 1.5990067921806537, Actual: 0.947947947947948
Model: 0.8304720502621633, Actual: 0.5295295295295295
Model: 0.6353471885434177, Actual: 1.0
Model: 0.9712740272257401, Actual: 0.7677677677677678
Model: 0.7125096049267523, Actual: 0.8658658658658659
Model: 3.4655914067931626, Actual: 0.5935935935935935
Model: 1.2276123430367845, Actual: 0.4924924924924925
Model: 2.5485954407151405, Actual: 1.0
Model: -0.2738867278427799, Actual: 0.6636636636636637
Model: -0.042121437011382046, Actual: 0.8028028028028028
Model: 0.7011221412445435, Actual: 0.943943943943944
Model: 1.7985155215567938, Actual: 0.7137137137137137
Model: 0.6311527040115383, Actual: 0.8438438438438438
Model: 2.4247064583013875, Actual: 1.0
Model: 3.344050177236509, Actual: 1.0
Model: -0.005009237754830087, Actual: 0.7617617617617618
Model: 1.5942209367922526, Actual: 0.7727727727727728
Model: -1.0699748243365488, A